version: "3.8"

services:
  # otw flask
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  backend-express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3500:3500"

    depends_on:
      - qdrant
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  flask-ai:
    build:
      context: ./backend/chatbotapp
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

    depends_on:
      - qdrant
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO  # Set logging level

volumes:
  qdrant_data:
    driver: local